# Generated by Django 4.1.4 on 2022-12-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=100)),
                ('profile', models.CharField(default='/static/favicon.ico', max_length=100)),
                ('sex', models.CharField(max_length=1, null=True)),
                ('registerdate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=50)),
                ('pic', models.CharField(default='/static/favicon.ico', max_length=150)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('price', models.FloatField()),
                ('publisher', models.CharField(max_length=100)),
                ('abstract', models.TextField()),
                ('type', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
