# Generated by Django 4.1.4 on 2022-12-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=100)),
                ('profile', models.CharField(default='/static/favicon.ico', max_length=100)),
                ('address', models.CharField(max_length=100, null=True)),
                ('sex', models.CharField(max_length=2, null=True)),
                ('registerdate', models.DateField(auto_now_add=True)),
                ('type', models.CharField(default='休闲娱乐', max_length=5)),
            ],
        ),
    ]
